package com.luv2code.springdemo;

public class CricketCoach implements Coach {
	
	
	private FortuneService fortuneService;
	
	//add 2 new private fields for emailaddress and team 
	
	private String emailAddress;
	private String team;
	
	
	//getters and setters 
	public String getEmailAddress() {
		System.out.println("cricketCoach: inside getter method - getEmailAddress");
		return emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		System.out.println("CricketCoach: inside setter method - setEmailAddress");

		this.emailAddress = emailAddress;
	}

	public String getTeam() {
		return team;
	}

	public void setTeam(String team) {
		System.out.println("CricketCoach: inside setter method - setTeam");
		this.team = team;
	}

	//no-arg const
	public CricketCoach(){
		System.out.println("CricketCoach:inside no-args contructor");
	}
	
	//setter method hack ctrl >source>generateG&S>setter only
	public void setFortuneService(FortuneService fortuneService) {
		System.out.println("CricketCoach: inside setter method - setFortuneService");
		this.fortuneService = fortuneService;
		
	}

	//generated by the adding in the coach interface with the creation of the CricketCoach class
	@Override
	public String getDailyWorkout() {
		return "practing hitting 10 perfect shots";
	}

	@Override
	public String getDailyFortune() {
		return fortuneService.getFortune();
	}



	

}
